#2) შექმენით პროგრამა რომელსაც შეეძლება დიალოგი თქვენთან (აირჩიეთ ნებისმიერი თემა) input გამოყენებით

print("hallo wats your name")
name=input("enter your name:",)
print("nice tu meet you", (name),("my name is nika"))
print("i em 16 years old how old are you")
age=input("enter your age:",)
lives=input("where are you from:",)
print("can you tall me sameting ebaut:",(lives))
input("")
print("wow sounds good. what are you busy with")
input("")
print("whats your faworit sport")
sport=input("")
print("wow i like", (sport), ("too do you want to play or wotch"), (sport), ("together"))
input("do you?:",)
print("ok, but when?")
time=input("enter time")
print("ok then lets meet et", (time), ("good bye see you soon"))